/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyfinalbd2;

import java.awt.Color;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.RowFilter;
import javax.swing.SwingConstants;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import javax.swing.table.TableRowSorter;
import proyfinalbd2.conexion.cliente;

/**
 *
 * @author ASUS
 */
public class ClienteAGREGAR extends javax.swing.JFrame {

    /**
     * Creates new form DatosCliente
     */
    private JTable tablaClientes;
    TableRowSorter<DefaultTableModel> SORTER;
    JTextField BUSCADOR;
    JComboBox COMBO;
    JLabel CONTADOR;
    public ClienteAGREGAR(JTable tablaClientes,TableRowSorter<DefaultTableModel> SORTER,JTextField BUSCADOR,JComboBox COMBO,JLabel CONTADOR) {
        this.tablaClientes=tablaClientes;
        this.BUSCADOR=BUSCADOR;
        this.SORTER=SORTER;
        this.COMBO=COMBO;
        this.CONTADOR=CONTADOR;
        initComponents();
        getContentPane().setBackground(Color.WHITE);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(ClienteTabla.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButtonCliente = new javax.swing.JButton();
        jTextFieldNombre = new javax.swing.JTextField();
        jTextFieldEmail = new javax.swing.JTextField();
        jTextFieldTelefono = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextFecha = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldDNI = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        Cabecera = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldRegion = new javax.swing.JTextField();
        jTextFieldProvincia = new javax.swing.JTextField();
        jTextFieldDistrito = new javax.swing.JTextField();
        jTextFieldCodPostal = new javax.swing.JTextField();
        jTextFieldDireccion = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel2.setText("Nombre");

        jLabel3.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel3.setText("Email");

        jLabel4.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel4.setText("Telefono");

        jButtonCliente.setBackground(new java.awt.Color(238, 0, 0));
        jButtonCliente.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jButtonCliente.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCliente.setText("Agregar");
        jButtonCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClienteActionPerformed(evt);
            }
        });

        jTextFieldNombre.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N

        jTextFieldEmail.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N

        jTextFieldTelefono.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel5.setText("Fecha");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("(Opcional)");

        jTextFecha.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel7.setText("DNI");

        jTextFieldDNI.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel8.setText("Datos de envio");

        Cabecera.setBackground(new java.awt.Color(174, 0, 0));
        Cabecera.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Nuevo Cliente");
        Cabecera.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, -1));

        jTextFieldRegion.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N

        jTextFieldProvincia.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N

        jTextFieldDistrito.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N

        jTextFieldCodPostal.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jTextFieldCodPostal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCodPostalActionPerformed(evt);
            }
        });

        jTextFieldDireccion.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jTextFieldDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDireccionActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel10.setText("Provincia");

        jLabel11.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel11.setText("Region");

        jLabel12.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel12.setText("Distrito");

        jLabel13.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel13.setText("Codigo Postal");

        jLabel14.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel14.setText("Direccion");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Cabecera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel7)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel3))
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldTelefono)
                                    .addComponent(jTextFieldDNI)
                                    .addComponent(jTextFieldNombre)
                                    .addComponent(jTextFieldEmail)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel10)
                                        .addComponent(jLabel11)
                                        .addComponent(jLabel12)
                                        .addComponent(jLabel13)
                                        .addComponent(jLabel14))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jTextFieldRegion, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
                                            .addComponent(jTextFieldProvincia)
                                            .addComponent(jTextFieldDistrito)
                                            .addComponent(jTextFieldCodPostal)
                                            .addComponent(jTextFieldDireccion))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jTextFecha))))))
                .addGap(49, 49, 49))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(192, 192, 192))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Cabecera, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTextFieldRegion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12)
                    .addComponent(jTextFieldDistrito, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jTextFieldCodPostal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jTextFieldDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addGap(26, 26, 26)
                .addComponent(jButtonCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClienteActionPerformed
        String dnibruto = jTextFieldDNI.getText().trim();
        String nom   = jTextFieldNombre.getText().trim();
        String email = jTextFieldEmail.getText().trim();
        String tel   = jTextFieldTelefono.getText().trim();
        String direccion = jTextFieldRegion.getText().trim()+"-"+jTextFieldProvincia.getText().trim()+"-"+jTextFieldDistrito.getText().trim()+"-"+jTextFieldCodPostal.getText().trim()+"-"+jTextFieldDireccion.getText().trim();
        String datos;

        // Validación de campos vacíos
        if (dnibruto.isEmpty() || nom.isEmpty() || email.isEmpty() || tel.isEmpty()|| direccion.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Todos los campos deben estar llenos.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Validación de email con '@'
        if (!email.contains("@")) {
            JOptionPane.showMessageDialog(null, "El correo electrónico debe contener '@'.", "Correo inválido", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Validación de número entero en teléfono
        int telefono;
        try {
            telefono = Integer.parseInt(tel); // Si no es un número, lanza excepción
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "El teléfono debe ser un número entero.", "Teléfono inválido", JOptionPane.WARNING_MESSAGE);
            return;
        }
        // Validación del dni, tiene que tener 8 digitos
        if (tel.length() != 9) {
            JOptionPane.showMessageDialog(null, "El Telefono debe tener exactamente 9 dígitos.", "Telefono inválido", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
         // Validación de número entero en dni
        int dni;
        try {
            dni = Integer.parseInt(dnibruto); // Si no es un número, lanza excepción
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "El dni debe ser un número entero.", "DNI inválido", JOptionPane.WARNING_MESSAGE);
            return;
        }
        // Validación del dni, tiene que tener 8 digitos
        if (dnibruto.length() != 8) {
            JOptionPane.showMessageDialog(null, "El DNI debe tener exactamente 8 dígitos.", "DNI inválido", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        //comprobamos si el usuario ingreso una fecha o no
        String fecha = jTextFecha.getText().trim();
        if(fecha.isEmpty()){
            //agregar cliente a la base de datos con la fecha actual por defecto
            cliente cl = new cliente(dni,nom,email,telefono,direccion);
            cl.insertarCliente();
            // Datos ingresados:
                    datos = "Cliente ingresado exitosamente.\n\n"
                     + "DNI: " + dni + "\n"
                     + "Nombre: " + nom + "\n"
                     + "Email: " + email + "\n"
                     + "Direccion: " + direccion + "\n"
                     + "Teléfono: " + telefono;
        }else {
            //validamos el formato de la fecha
            java.sql.Date fechasql;
            try {
                fechasql = java.sql.Date.valueOf(fecha);
                //insertamos el cliente en la bd con la fecha especificada
                cliente c = new cliente(dni,nom,email,telefono,direccion,fechasql);
                c.insertarClienteConFecha();
                // Datos ingresados:
                     datos = "Cliente ingresado exitosamente.\n\n"
                     + "DNI: " + dni + "\n"        
                     + "Nombre: " + nom + "\n"
                     + "Email: " + email + "\n"
                     + "Teléfono: " + telefono + "\n"
                     + "Email: " + direccion + "\n"
                     + "Fecha de registro: " + fecha;
            }catch (IllegalArgumentException e) {
                JOptionPane.showMessageDialog(null, "La fecha debe tener el sigueinte fomato (yyyy-mm-dd)", "Fecha inválida", JOptionPane.WARNING_MESSAGE);
                return;
            }
        }

        
        

        JOptionPane.showMessageDialog(this, datos, "Datos Guardados", JOptionPane.INFORMATION_MESSAGE);
        
        BUSCADOR.setText("");      // limpia buscador
        SORTER.setRowFilter(null);
        
        
        
        //actualizar tabla de clientes
        cliente.mostrarClientesEnTabla(tablaClientes);
        TableColumnModel columnModel = tablaClientes.getColumnModel();
        columnModel.getColumn(0).setPreferredWidth(5);//id
        columnModel.getColumn(1).setPreferredWidth(5);//dni
        columnModel.getColumn(2).setPreferredWidth(250);////nombre
        columnModel.getColumn(3).setPreferredWidth(250);//email
        columnModel.getColumn(4).setPreferredWidth(5);//telefono
        columnModel.getColumn(5).setPreferredWidth(250);//direccion
        columnModel.getColumn(6).setPreferredWidth(5);//fecha
        
        
//      
        
        
        
        DefaultTableCellRenderer centrado = new DefaultTableCellRenderer();
        centrado.setHorizontalAlignment(SwingConstants.CENTER);
        
        
        //  Aplicar el centrado a la columna "id" (índice 0)
        tablaClientes.getColumnModel().getColumn(0).setCellRenderer(centrado);
        tablaClientes.getColumnModel().getColumn(1).setCellRenderer(centrado);
        tablaClientes.getColumnModel().getColumn(4).setCellRenderer(centrado);
        tablaClientes.getColumnModel().getColumn(6).setCellRenderer(centrado);
        
        DefaultTableModel modelo = (DefaultTableModel) tablaClientes.getModel();
            SORTER = new TableRowSorter<>(modelo); // ¡aquí sí lo llenas!
            tablaClientes.setRowSorter(SORTER);
        
        BUSCADOR.getDocument().addDocumentListener(new DocumentListener() {
    @Override
    public void insertUpdate(DocumentEvent e) { filtrar(); }
    @Override
    public void removeUpdate(DocumentEvent e) { filtrar(); }
    @Override
    public void changedUpdate(DocumentEvent e) { filtrar(); }

    private void filtrar() {
        String texto = BUSCADOR.getText();
        if (texto.trim().length() == 0) {
            SORTER.setRowFilter(null);
        } else {
            SORTER.setRowFilter(RowFilter.regexFilter("(?i)" + texto, COMBO.getSelectedIndex()));
        }
    }
});
   
        
        //actualizar los registros
        int n = tablaClientes.getRowCount();
        CONTADOR.setText(n+" CLIENTES REGISTRADOS");
        
        // Cerrar solo esta ventana
        dispose();

        
    }//GEN-LAST:event_jButtonClienteActionPerformed

    private void jTextFieldCodPostalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCodPostalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCodPostalActionPerformed

    private void jTextFieldDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDireccionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClienteAGREGAR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClienteAGREGAR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClienteAGREGAR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClienteAGREGAR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form 
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClienteAGREGAR().setVisible(true);
            }
        });*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Cabecera;
    private javax.swing.JButton jButtonCliente;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextFecha;
    private javax.swing.JTextField jTextFieldCodPostal;
    private javax.swing.JTextField jTextFieldDNI;
    private javax.swing.JTextField jTextFieldDireccion;
    private javax.swing.JTextField jTextFieldDistrito;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldProvincia;
    private javax.swing.JTextField jTextFieldRegion;
    private javax.swing.JTextField jTextFieldTelefono;
    // End of variables declaration//GEN-END:variables
}
