/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyfinalbd2;

import com.formdev.flatlaf.FlatLightLaf;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import proyfinalbd2.conexion.producto;
import proyfinalbd2.conexion.empleado;


/**
 *
 * @author ASUS
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form DatosCliente
     */
    public static String usuario;
    public static String rol;
    //usuarios y claves predeterminadas
    private final String usuarioBase = "usuario";
    private final String claveUsuarioBase = "usuario123";
    private final String moderador = "moderador";
    private final String claveModerador = "moderador123";
    private final String admin = "administrador";
    private final String claveAdmin = "admin123";
    public Login() {
        initComponents();
        setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Fondo = new javax.swing.JPanel();
        jLabelIniciarSesion = new javax.swing.JLabel();
        jButtonSalir = new javax.swing.JButton();
        jButtonIniciarSesion = new javax.swing.JButton();
        jLabelUsuario = new javax.swing.JLabel();
        jLabelContraseña = new javax.swing.JLabel();
        Separador = new javax.swing.JLabel();
        Separador1 = new javax.swing.JLabel();
        jTextFieldClave = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jTextFieldUsuario = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        Fondo.setBackground(new java.awt.Color(255, 255, 255));
        Fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelIniciarSesion.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabelIniciarSesion.setText("INICIAR SESIÓN");
        Fondo.add(jLabelIniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 190, -1));

        jButtonSalir.setBackground(new java.awt.Color(209, 0, 0));
        jButtonSalir.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jButtonSalir.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSalir.setText("Salir");
        jButtonSalir.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtonSalir.setBorderPainted(false);
        jButtonSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });
        Fondo.add(jButtonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, 101, 40));

        jButtonIniciarSesion.setBackground(new java.awt.Color(209, 0, 0));
        jButtonIniciarSesion.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jButtonIniciarSesion.setForeground(new java.awt.Color(255, 255, 255));
        jButtonIniciarSesion.setText("Entrar");
        jButtonIniciarSesion.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtonIniciarSesion.setBorderPainted(false);
        jButtonIniciarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIniciarSesionActionPerformed(evt);
            }
        });
        Fondo.add(jButtonIniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 330, 40));

        jLabelUsuario.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabelUsuario.setText("Usuario");
        Fondo.add(jLabelUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, 24));

        jLabelContraseña.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabelContraseña.setText("Contraseña");
        Fondo.add(jLabelContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));

        Separador.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        Separador.setText("___________________________________________________________");
        Fondo.add(Separador, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, -1, -1));

        Separador1.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        Separador1.setText("___________________________________________________________");
        Fondo.add(Separador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));

        jTextFieldClave.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jTextFieldClave.setBorder(null);
        jTextFieldClave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldClaveActionPerformed(evt);
            }
        });
        Fondo.add(jTextFieldClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 330, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Diseño sin título (2).png"))); // NOI18N
        jLabel2.setText("jLabel2");
        Fondo.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 0, 320, 600));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/logo-distribuidora.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        Fondo.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 70, 60));

        jPanel1.setBackground(new java.awt.Color(209, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );

        Fondo.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 0, 20, 590));

        jPanel2.setBackground(new java.awt.Color(209, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );

        Fondo.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, 10, 590));

        jTextFieldUsuario.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jTextFieldUsuario.setBorder(null);
        jTextFieldUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUsuarioActionPerformed(evt);
            }
        });
        Fondo.add(jTextFieldUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 330, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Fondo, javax.swing.GroupLayout.PREFERRED_SIZE, 794, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Fondo, javax.swing.GroupLayout.PREFERRED_SIZE, 588, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIniciarSesionActionPerformed
        String usuarioIngresado = jTextFieldUsuario.getText();
        String clave = jTextFieldClave.getText();
        
        //validamos que se haya llenado los dos campos
        if(usuarioIngresado.isEmpty() || clave.isEmpty()){
            JOptionPane.showMessageDialog(null, "Todos los campos deben estar llenos.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        
        rol = empleado.validarEmpleado(usuarioIngresado,clave);

        if (rol != null) {
            // Acceso válido
                JOptionPane.showMessageDialog(
                    null,
                    "Inicio de sesión exitoso.\nBienvenido, " + usuarioIngresado + ".\nRol: " + rol,
                    "Acceso concedido",
                    JOptionPane.INFORMATION_MESSAGE
                );

        } else {
            // Acceso inválido
            JOptionPane.showMessageDialog(
                null,
                "Usuario o contraseña incorrectos.\nPor favor, inténtelo de nuevo.",
                "Error de autenticación",
                JOptionPane.ERROR_MESSAGE
            );
            
            jTextFieldUsuario.setText("");
            jTextFieldClave.setText("");
            return;
        }
        
        
        
        
        
//        //validamos si se ingreso las credenciales correctas
//        if(usuarioIngresado.equals(usuarioBase) && clave.equals(claveUsuarioBase)){
//            usuario = usuarioIngresado;
//        }else if(usuarioIngresado.equals(moderador) && clave.equals(claveModerador)){
//            usuario = usuarioIngresado;
//        }else if(usuarioIngresado.equals(admin) && clave.equals(claveAdmin)){
//            usuario = usuarioIngresado;
//        }else {
//            JOptionPane.showMessageDialog(null, "Usuario o Clave inválido. Intente nuevamente", "Advertencia", JOptionPane.WARNING_MESSAGE);
//            jTextFieldUsuario.setText("");
//            jTextFieldClave.setText("");
//            return;
//        }
        this.dispose();
        new MenuPrincipal().setVisible(true);
    }//GEN-LAST:event_jButtonIniciarSesionActionPerformed

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jTextFieldClaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldClaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldClaveActionPerformed

    private void jTextFieldUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel( new FlatLightLaf() );
        } catch( Exception ex ) {
            System.err.println( "Failed to initialize LaF" );
        }

        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form 
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProductoAGREGAR().setVisible(true);
            }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Fondo;
    private javax.swing.JLabel Separador;
    private javax.swing.JLabel Separador1;
    private javax.swing.JButton jButtonIniciarSesion;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelContraseña;
    private javax.swing.JLabel jLabelIniciarSesion;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextFieldClave;
    private javax.swing.JTextField jTextFieldUsuario;
    // End of variables declaration//GEN-END:variables
}
