/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyfinalbd2;

import static com.sun.java.accessibility.util.SwingEventMonitor.addListSelectionListener;
import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.Date;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.RowFilter;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import javax.swing.table.TableRowSorter;
import proyfinalbd2.conexion.cliente;

/**
 *
 * @author ASUS
 */

public class PedidoEscogerCliente extends javax.swing.JFrame {
    private DefaultTableModel modelo;
    public static String nombre;
    public static String id;
    public static String direccion;
    public static Date pFecha;
    public JTable tablaPedidosMenuPrincipal;
    TableRowSorter<DefaultTableModel> SORTER;
    JTextField BUSCADOR;
    JComboBox COMBO;
    
    

        private void filtrar(TableRowSorter<DefaultTableModel> sorter) {
        String texto = jTextBuscarCliente.getText();
        int columna = jComboClientesColumnas.getSelectedIndex();
        
        if (texto.trim().length() == 0) {
            sorter.setRowFilter(null);
        } else {
            sorter.setRowFilter(RowFilter.regexFilter("(?i)" + texto, columna));
        }
        

        
        }    
    


    
    /**
     * Creates new form PedidoEscogerCliente
     */
    public PedidoEscogerCliente(JTable tablaPedidosMenuPrincipal,TableRowSorter<DefaultTableModel> SORTER,JTextField BUSCADOR,JComboBox COMBO) {
        initComponents();
        this.tablaPedidosMenuPrincipal=tablaPedidosMenuPrincipal;
        this.BUSCADOR=BUSCADOR;
        this.SORTER=SORTER;
        this.COMBO=COMBO;
        cliente.mostrarIdYNombresEnTabla(jTableClientes);
        TableColumnModel columnModel = jTableClientes.getColumnModel();
        
        columnModel.getColumn(0).setPreferredWidth(30);//id
        columnModel.getColumn(1).setPreferredWidth(270);//nombre
        columnModel.getColumn(2).setPreferredWidth(270);////direccion
   

        modelo = (DefaultTableModel) jTableClientes.getModel(); // Asignas el modelo
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(modelo);
        jTableClientes.setRowSorter(sorter); // Conectas el sorter a la tabla
        setLocationRelativeTo(null); // Centrar ventana
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
        
        	getContentPane().setBackground(Color.WHITE);
        
        jTableClientes.getSelectionModel().addListSelectionListener(evt -> {
    if (!evt.getValueIsAdjusting()) {
        int fila = jTableClientes.getSelectedRow();
        if (fila >= 0) {
            DefaultTableModel modelo = (DefaultTableModel) jTableClientes.getModel();
            String direccion = modelo.getValueAt(fila, 2).toString();
            jTextDireccion.setText(direccion);
            
        }
    }
});

        
    // Vinculas el filtro con el JTextField
    jTextBuscarCliente.getDocument().addDocumentListener(new DocumentListener() {
        public void insertUpdate(DocumentEvent e) { filtrar(sorter); }
        public void removeUpdate(DocumentEvent e) { filtrar(sorter); }
        public void changedUpdate(DocumentEvent e) { filtrar(sorter); }
    });

    }
    
    

        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane5 = new javax.swing.JScrollPane();
        jTableProducto1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTableClientes = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jTextBuscarCliente = new javax.swing.JTextField();
        jDateChooser = new com.toedter.calendar.JDateChooser();
        jButtonCrearPedido = new javax.swing.JButton();
        jComboClientesColumnas = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jTextDireccion = new javax.swing.JTextField();
        Cabecera = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        jTableProducto1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "Nombre"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane5.setViewportView(jTableProducto1);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setText("Seleccione un cliente");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Seleccione un cliente");

        jTableClientes.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jTableClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "Nombre"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane6.setViewportView(jTableClientes);

        jLabel4.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel4.setText("Seleccione un fecha");

        jTextBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextBuscarClienteActionPerformed(evt);
            }
        });

        jButtonCrearPedido.setBackground(new java.awt.Color(238, 0, 0));
        jButtonCrearPedido.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButtonCrearPedido.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCrearPedido.setText("Crear pedido");
        jButtonCrearPedido.setBorder(null);
        jButtonCrearPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCrearPedidoActionPerformed(evt);
            }
        });

        jComboClientesColumnas.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jComboClientesColumnas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID del Cliente", "Nombre" }));
        jComboClientesColumnas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboClientesColumnasActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel5.setText("Direccion de entrega");

        Cabecera.setBackground(new java.awt.Color(174, 0, 0));
        Cabecera.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Nuevo Pedido");
        Cabecera.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 730, -1));

        jLabel6.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel6.setText("Buscador");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Cabecera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextDireccion))
                        .addGap(10, 10, 10))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(jTextBuscarCliente)
                                .addGap(18, 18, 18)
                                .addComponent(jComboClientesColumnas, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButtonCrearPedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Cabecera, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 20, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextBuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboClientesColumnas, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jButtonCrearPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCrearPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCrearPedidoActionPerformed
        // TODO add your handling code here:
        pFecha = jDateChooser.getDate(); // Obtenemos la fecha
        direccion = jTextDireccion.getText().trim();
        int fila = jTableClientes.getSelectedRow(); // Obtenemos la fila seleccionada

        // Validamos que se haya seleccionado un cliente
        if (fila < 0) {
            JOptionPane.showMessageDialog(this,
                "Debe seleccionar un cliente.",
                "Error", JOptionPane.ERROR_MESSAGE);
            return; // detenemos el flujo
        }

        // Validamos que se haya seleccionado una fecha
        if (pFecha == null) {
            JOptionPane.showMessageDialog(this,
                "Debe seleccionar una fecha.",
                "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        // Validamos que se haya colocado una direccion
        if (direccion.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                "Debe Colocar una direcion",
                "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        

        // Si ambas validaciones pasan, seguimos
        long fecha = pFecha.getTime();
        java.sql.Date fecha_sql = new java.sql.Date(fecha);

        int filaReal = jTableClientes.convertRowIndexToModel(fila);
        id = modelo.getValueAt(filaReal, 0).toString(); // ID del cliente
        nombre = modelo.getValueAt(filaReal, 1).toString(); // Nombre del cliente

        JOptionPane.showMessageDialog(this,
            "Pedido creado exitosamente:\n" +
            "ID Cliente: " + id + "\n" +
            "Nombre: " + nombre + "\n" +
            "Direccion de entrega: " + direccion + "\n" +
            "Fecha: " + fecha_sql,
            "Éxito", JOptionPane.INFORMATION_MESSAGE);

        // Abrimos la ventana siguiente
        new PedidoAGREGAR(this.tablaPedidosMenuPrincipal,
        this.SORTER,        
        this.BUSCADOR,
        this.COMBO).setVisible(true);
        this.dispose();

    }//GEN-LAST:event_jButtonCrearPedidoActionPerformed

    private void jTextBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextBuscarClienteActionPerformed
//    // TODO add your handling code here:
//
//    jTableClientes = new JTable(modelo);
//    TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(modelo);
//    jTableClientes.setRowSorter(sorter);
//    // Campo de búsqueda
//
//    jTextBuscarCliente.getDocument().addDocumentListener(new DocumentListener() {
//        public void insertUpdate(DocumentEvent e) { filtrar(sorter); }
//        public void removeUpdate(DocumentEvent e) { filtrar(sorter); }
//        public void changedUpdate(DocumentEvent e) { filtrar(sorter); }
//    });
//
//
    }//GEN-LAST:event_jTextBuscarClienteActionPerformed

    private void jComboClientesColumnasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboClientesColumnasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboClientesColumnasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PedidoEscogerCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PedidoEscogerCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PedidoEscogerCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PedidoEscogerCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PedidoEscogerCliente().setVisible(true);
            }
        });*/

        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Cabecera;
    private javax.swing.JButton jButtonCrearPedido;
    private javax.swing.JComboBox<String> jComboClientesColumnas;
    private com.toedter.calendar.JDateChooser jDateChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTable jTableClientes;
    private javax.swing.JTable jTableProducto1;
    private javax.swing.JTextField jTextBuscarCliente;
    private javax.swing.JTextField jTextDireccion;
    // End of variables declaration//GEN-END:variables
}
