/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyfinalbd2;

import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.SwingConstants;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import javax.swing.table.TableRowSorter;
import proyfinalbd2.conexion.producto;

/**
 *
 * @author ASUS
 */
public class ProductosTabla extends javax.swing.JFrame {

    /**
     * Creates new form Productos
     */
            int id_producto;
            public static String ProductoId;
            public static String cod;
            public static String nombre;
            public static String descripcion;
            public static String precio;
            public static String idsubcat;
            public static String stock;
            
            private DefaultTableModel modelo;
            TableRowSorter<DefaultTableModel> sorter;
            
            public static int filaseleccionada;
            
            
            
        private void filtrar(TableRowSorter<DefaultTableModel> sorter) {
        String texto = jTextFieldBuscarProducto.getText();
        
        int columna = jComboColumnasProductos.getSelectedIndex();
        
        if (texto.trim().length() == 0) {
            sorter.setRowFilter(null);
        } else {
            sorter.setRowFilter(RowFilter.regexFilter("(?i)" + texto, columna));
        }    
        }
            
        
    
    public ProductosTabla() {
        initComponents();
        setLocationRelativeTo(null);
        producto.mostrarProductosEnTabla(jTableProductos);
        EstiloTabla();
        xProductos();
        
        //fondo blanco
        getContentPane().setBackground(new Color(255, 255, 255)); // blanco

        
        modelo = (DefaultTableModel) jTableProductos.getModel(); // Asignas el modelo
        sorter = new TableRowSorter<>(modelo);
        jTableProductos.setRowSorter(sorter); // Conectas el sorter a la tabla
        
        // Vinculas el filtro con el JTextField
         jTextFieldBuscarProducto.getDocument().addDocumentListener(new DocumentListener() {
        public void insertUpdate(DocumentEvent e) { filtrar(sorter); }
        public void changedUpdate(DocumentEvent e) { filtrar(sorter); }
        public void removeUpdate(DocumentEvent e) { filtrar(sorter); }
    });
        
       // Agregar un listener al modelo
        modelo.addTableModelListener(new javax.swing.event.TableModelListener() {
            @Override
            public void tableChanged(javax.swing.event.TableModelEvent e) {
                int totalFilas = modelo.getRowCount();
                jLabelProductosRegistrados.setText(totalFilas + " PRODUCTOS REGISTRADOS");
            }
        });
         
         
         
        
    }   
    public void EstiloTabla(){
        TableColumnModel columnModel = jTableProductos.getColumnModel();
        columnModel.getColumn(0).setPreferredWidth(5);//id
        columnModel.getColumn(1).setPreferredWidth(40);//codigo
        columnModel.getColumn(2).setPreferredWidth(250);////nombre
        columnModel.getColumn(3).setPreferredWidth(400);//descripcion
        columnModel.getColumn(4).setPreferredWidth(30);//Subcategoria
        columnModel.getColumn(5).setPreferredWidth(5);//precio 
        columnModel.getColumn(6).setPreferredWidth(5);//Stock
        
        DefaultTableCellRenderer centrado = new DefaultTableCellRenderer();
        centrado.setHorizontalAlignment(SwingConstants.CENTER);

        //  Aplicar el centrado a la columna "id" (índice 0)
        jTableProductos.getColumnModel().getColumn(0).setCellRenderer(centrado);
        jTableProductos.getColumnModel().getColumn(1).setCellRenderer(centrado);
        
        jTableProductos.getColumnModel().getColumn(5).setCellRenderer(centrado);
         jTableProductos.getColumnModel().getColumn(6).setCellRenderer(centrado);
    
    }
    
    public void xProductos(){
        int n = jTableProductos.getRowCount();
        jLabelProductosRegistrados.setText(n+" PRODUCTOS REGISTRADOS");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelProductosRegistrados = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProductos = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        Cabecera = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jComboColumnasProductos = new javax.swing.JComboBox<>();
        jTextFieldBuscarProducto = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jButtonAddProducto = new javax.swing.JButton();
        jButtonModProducto = new javax.swing.JButton();
        jButtonEliminarProducto = new javax.swing.JButton();
        jButtonVolver = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabelProductosRegistrados.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabelProductosRegistrados.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelProductosRegistrados.setText("n Productos Registrados");

        jTableProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "id_producto", "Codigo", "nombre", "Descripcion", "ID_Subcategoria", "precio", "Stock"
            }
        ));
        jTableProductos.setMinimumSize(new java.awt.Dimension(90, 80));
        jScrollPane1.setViewportView(jTableProductos);

        jLabel3.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel3.setText("Buscador ");

        Cabecera.setBackground(new java.awt.Color(171, 0, 0));
        Cabecera.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Productos");
        Cabecera.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, 3, 1510, 50));

        jPanel2.setBackground(new java.awt.Color(224, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1510, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        Cabecera.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 1510, 10));

        jComboColumnasProductos.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jComboColumnasProductos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID", "Codigo", "Nombre", "Descripcion", "ID-Subcategoria", "Precio", "Stock" }));
        jComboColumnasProductos.setSelectedIndex(2);
        jComboColumnasProductos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jTextFieldBuscarProducto.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jTextFieldBuscarProducto.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextFieldBuscarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBuscarProductoActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(238, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonAddProducto.setBackground(new java.awt.Color(238, 0, 0));
        jButtonAddProducto.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jButtonAddProducto.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAddProducto.setText("Agregar");
        jButtonAddProducto.setBorder(null);
        jButtonAddProducto.setBorderPainted(false);
        jButtonAddProducto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAddProducto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonAddProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddProductoActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonAddProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 80));

        jButtonModProducto.setBackground(new java.awt.Color(238, 0, 0));
        jButtonModProducto.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jButtonModProducto.setForeground(new java.awt.Color(255, 255, 255));
        jButtonModProducto.setText("Modificar ");
        jButtonModProducto.setBorder(null);
        jButtonModProducto.setBorderPainted(false);
        jButtonModProducto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonModProducto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonModProducto.setPreferredSize(new java.awt.Dimension(168, 24));
        jButtonModProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModProductoActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonModProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 210, 80));

        jButtonEliminarProducto.setBackground(new java.awt.Color(238, 0, 0));
        jButtonEliminarProducto.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jButtonEliminarProducto.setForeground(new java.awt.Color(255, 255, 255));
        jButtonEliminarProducto.setText("Eliminar ");
        jButtonEliminarProducto.setBorder(null);
        jButtonEliminarProducto.setBorderPainted(false);
        jButtonEliminarProducto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonEliminarProducto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonEliminarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarProductoActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonEliminarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 210, 90));

        jButtonVolver.setBackground(new java.awt.Color(238, 0, 0));
        jButtonVolver.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jButtonVolver.setForeground(new java.awt.Color(255, 255, 255));
        jButtonVolver.setText("Volver al menú");
        jButtonVolver.setBorder(null);
        jButtonVolver.setBorderPainted(false);
        jButtonVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonVolver.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 210, 100));

        jButtonSalir.setBackground(new java.awt.Color(238, 0, 0));
        jButtonSalir.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jButtonSalir.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSalir.setText("Salir");
        jButtonSalir.setBorder(null);
        jButtonSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 210, 40));

        jPanel3.setBackground(new java.awt.Color(238, 0, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(238, 0, 0));
        jButton1.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("LIMPIAR");
        jButton1.setBorder(null);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1254, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldBuscarProducto)
                        .addGap(18, 18, 18)
                        .addComponent(jComboColumnasProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelProductosRegistrados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(24, Short.MAX_VALUE))
            .addComponent(Cabecera, javax.swing.GroupLayout.DEFAULT_SIZE, 1512, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Cabecera, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabelProductosRegistrados, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextFieldBuscarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jComboColumnasProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(13, 13, 13)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAddProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddProductoActionPerformed
        //validamos permisos según el rol
        if("Supervisor".equals(Login.rol) || "Vendedor".equals(Login.rol)){
            JOptionPane.showMessageDialog(null, "Usted no cuenta con los permisos suficientes para acceder a este apartado",
                "Acceso Denegado", JOptionPane.WARNING_MESSAGE);
            return;
        }
        new ProductoAGREGAR(jTableProductos,sorter,jTextFieldBuscarProducto,jComboColumnasProductos,jLabelProductosRegistrados).setVisible(true);
    }//GEN-LAST:event_jButtonAddProductoActionPerformed

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jButtonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverActionPerformed
        new MenuPrincipal().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonVolverActionPerformed

    private void jButtonModProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModProductoActionPerformed
        //validamos permisos según el rol
        if("Supervisor".equals(Login.rol) || "Vendedor".equals(Login.rol)){
            JOptionPane.showMessageDialog(null, "Usted no cuenta con los permisos suficientes para acceder a este apartado",
                "Acceso Denegado", JOptionPane.WARNING_MESSAGE);
            return;
        }
        int fila = jTableProductos.getSelectedRow(); // Obtenemos la fila seleccionada

        // Validamos que se haya seleccionado un cliente
        if (fila < 0) {
            JOptionPane.showMessageDialog(this,
                "Debe seleccionar un producto.",
                "Error", JOptionPane.ERROR_MESSAGE);
            return; // detenemos el flujo
        }
        
        //guardamos los datos de la fila seleccionada
        ProductoId = jTableProductos.getValueAt(fila, 0).toString(); // ID del producto seleccionado
        cod = jTableProductos.getValueAt(fila, 1).toString(); // codigo del producto seleccionado
        nombre = jTableProductos.getValueAt(fila, 2).toString(); // nombre del producto seleccionado
        descripcion = jTableProductos.getValueAt(fila,3).toString(); // descripcion del producto seleccionado
        String valor = jTableProductos.getValueAt(fila, 4).toString(); // IDsubcategoria del producto seleccionado
        idsubcat = valor.split("-")[0]; // Se extrae solo el ID de la subcategoria del "ID-Categoria"
        precio = jTableProductos.getValueAt(fila, 5).toString(); // precio del producto seleccionado
        stock = jTableProductos.getValueAt(fila, 6).toString(); // stock del producto seleccionado
        new ProductoMODIFICAR(jTableProductos,sorter,jTextFieldBuscarProducto,jComboColumnasProductos).setVisible(true);
    }//GEN-LAST:event_jButtonModProductoActionPerformed

    private void jButtonEliminarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarProductoActionPerformed
       //validamos permisos según el rol
        if("Supervisor".equals(Login.rol) || "Vendedor".equals(Login.rol)){
            JOptionPane.showMessageDialog(null, "Usted no cuenta con los permisos suficientes para acceder a este apartado",
                "Acceso Denegado", JOptionPane.WARNING_MESSAGE);
            return;
        }
        int fila = jTableProductos.getSelectedRow(); // Obtenemos la fila seleccionada

        // Validamos que se haya seleccionado un cliente
        if (fila < 0) {
            JOptionPane.showMessageDialog(this,
                "Debe seleccionar una fila.",
                "Error", JOptionPane.ERROR_MESSAGE);
            return; // detenemos el flujo
        }
        
        //guardamos los datos de la fila seleccionada
        ProductoId = jTableProductos.getValueAt(fila, 0).toString(); // ID del producto seleccionado
        cod = jTableProductos.getValueAt(fila, 1).toString(); // codigo del producto seleccionado
        nombre = jTableProductos.getValueAt(fila, 2).toString(); // nombre del producto seleccionado
        descripcion = jTableProductos.getValueAt(fila,3).toString(); // descripcion del producto seleccionado
        precio = jTableProductos.getValueAt(fila, 4).toString(); // precio del producto seleccionado
        idsubcat = jTableProductos.getValueAt(fila, 5).toString(); // IDsubcategoria del producto seleccionado
        stock = jTableProductos.getValueAt(fila, 6).toString(); // stock del producto seleccionado
            
            
                try{    
                    id_producto = Integer.parseInt(ProductoId);

                    int opcion = JOptionPane.showConfirmDialog(
                            null,
                            "¿Está seguro de que desea eliminar al producto?\n¡Este será borrado permanentemente de la base de datos!",
                            "Confirmar Eliminación",
                            JOptionPane.YES_NO_OPTION,
                            JOptionPane.WARNING_MESSAGE
                    );

                    if (opcion == JOptionPane.YES_OPTION) {
                            producto p = new producto();
                            p.eliminarProducto(id_producto);
                            JOptionPane.showMessageDialog(
                                null,
                                "El producto de ID: "+id_producto+" ha sido eliminado correctamente.",
                                "Eliminado",
                                JOptionPane.INFORMATION_MESSAGE
                            );
                            
                            jTextFieldBuscarProducto.setText("");      // limpia buscador
                            sorter.setRowFilter(null);
                            
                            //actualizar productos de la tabla
                            producto.mostrarProductosEnTabla(jTableProductos);
                                    EstiloTabla();
                             sorter = new TableRowSorter<DefaultTableModel>((DefaultTableModel) jTableProductos.getModel());
                            jTableProductos.setRowSorter(sorter);       
                                    

                    } else {
                            JOptionPane.showMessageDialog(
                                null,
                                "Operación cancelada. El producto no fue eliminado.",
                                "Cancelado",
                                JOptionPane.INFORMATION_MESSAGE
                        );
                    }

                }catch(NumberFormatException e){
                            JOptionPane.showMessageDialog(null,"¡El ID del producto tiene que ser un entero!","Alerta",JOptionPane.WARNING_MESSAGE);
                }            
    
    }//GEN-LAST:event_jButtonEliminarProductoActionPerformed

    private void jTextFieldBuscarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBuscarProductoActionPerformed
        jTableProductos = new JTable(modelo);
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(modelo);
        jTableProductos.setRowSorter(sorter);
        // Campo de búsqueda

        jTextFieldBuscarProducto.getDocument().addDocumentListener(new DocumentListener() {
            public void insertUpdate(DocumentEvent e) { filtrar(sorter); }
            public void removeUpdate(DocumentEvent e) { filtrar(sorter); }
            public void changedUpdate(DocumentEvent e) { filtrar(sorter); }
        });
    }//GEN-LAST:event_jTextFieldBuscarProductoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jTextFieldBuscarProducto.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductosTabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProductosTabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProductosTabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductosTabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProductosTabla().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Cabecera;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonAddProducto;
    private javax.swing.JButton jButtonEliminarProducto;
    private javax.swing.JButton jButtonModProducto;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JButton jButtonVolver;
    private javax.swing.JComboBox<String> jComboColumnasProductos;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelProductosRegistrados;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableProductos;
    private javax.swing.JTextField jTextFieldBuscarProducto;
    // End of variables declaration//GEN-END:variables
}
