/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyfinalbd2;

import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import javax.swing.table.TableRowSorter;
import static proyfinalbd2.PedidoEscogerCliente.pFecha;
import static proyfinalbd2.RutasCREAR.rFecha;
import proyfinalbd2.conexion.detalle_pedido;
import proyfinalbd2.conexion.pedidos;
import proyfinalbd2.conexion.producto;
import proyfinalbd2.conexion.ruta;

/**
 *
 * @author ASUS
 */
public class RutasMOD extends javax.swing.JFrame {
    private DefaultTableModel modelo;
    private DefaultTableModel modelo2;
    TableRowSorter<DefaultTableModel> sorter;
    TableRowSorter<DefaultTableModel> sorter2;
    public JTable tablaPedidosMenuPrincipal;
    
    

    private void filtrar(TableRowSorter<DefaultTableModel> sorter) {
        String texto = jTextFieldBuscarProducto.getText();
        
        int columna = jComboColumnasProductos.getSelectedIndex();
        
        if (texto.trim().length() == 0) {
            sorter.setRowFilter(null);
        } else {
            sorter.setRowFilter(RowFilter.regexFilter("(?i)" + texto, columna));
        }
        
        
        
    }
    private void filtrar2(TableRowSorter<DefaultTableModel> sorter2) {
        String texto = jTextFieldBuscarPPedido.getText();
        int columna = jComboColumnasPedidos.getSelectedIndex();
        
        if (texto.trim().length() == 0) {
            sorter2.setRowFilter(null);
        } else {
            sorter2.setRowFilter(RowFilter.regexFilter("(?i)" + texto, columna));
        }
    }
    
    

    /**
     * Creates new form PedidoEscogerCliente
     */
    public RutasMOD(JTable tablaPedidosMenuPrincipal) {
        initComponents();
        this.tablaPedidosMenuPrincipal=tablaPedidosMenuPrincipal;
        setLocationRelativeTo(null);
        setDefaultCloseOperation(RutasMOD.DISPOSE_ON_CLOSE);
        
        pedidos.obtenerTablaPedidosParaRuta(jTablePedidos,"IS NULL");
        pedidos.obtenerPedidosEnRuta(jTablePedidosDeRuta,RutasTabla.id_ruta);

        jLabelNomRuta.setText(RutasTabla.id_ruta+ " - " + RutasTabla.nomruta);

        
        
        
        modelo = (DefaultTableModel) jTablePedidos.getModel(); // Asignas el modelo
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(modelo);
        jTablePedidos.setRowSorter(sorter); // Conectas el sorter a la tabla
            
        modelo2 = (DefaultTableModel) jTablePedidosDeRuta.getModel(); // Asignas el modelo
        TableRowSorter<DefaultTableModel> sorter2 = new TableRowSorter<>(modelo2);
        jTablePedidosDeRuta.setRowSorter(sorter2); // Conectas el sorter a la tabla

    // Vinculas el filtro con el JTextField
    jTextFieldBuscarProducto.getDocument().addDocumentListener(new DocumentListener() {
        public void insertUpdate(DocumentEvent e) { filtrar(sorter); }
        public void changedUpdate(DocumentEvent e) { filtrar(sorter); }
        public void removeUpdate(DocumentEvent e) { filtrar(sorter); }
    });
       // Vinculas el filtro con el JTextField
    jTextFieldBuscarPPedido.getDocument().addDocumentListener(new DocumentListener() {
        public void insertUpdate(DocumentEvent e) { filtrar2(sorter2); }
        public void changedUpdate(DocumentEvent e) { filtrar2(sorter2); }
        public void removeUpdate(DocumentEvent e) { filtrar2(sorter2); }
    });
    
    

    }
    /**
     * Creates new form DatosCliente
     */


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jButtonActualizarRuta = new javax.swing.JButton();
        jTextFieldBuscarProducto = new javax.swing.JTextField();
        jButtonAsignarPedido = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePedidosDeRuta = new javax.swing.JTable();
        jLabelNomRuta = new javax.swing.JLabel();
        jButtonQuitarPedido = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldBuscarPPedido = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTablePedidos = new javax.swing.JTable();
        jComboColumnasProductos = new javax.swing.JComboBox<>();
        jComboColumnasPedidos = new javax.swing.JComboBox<>();
        Cabecera = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel2.setText("Ruta:");

        jButtonActualizarRuta.setBackground(new java.awt.Color(238, 0, 0));
        jButtonActualizarRuta.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jButtonActualizarRuta.setForeground(new java.awt.Color(255, 255, 255));
        jButtonActualizarRuta.setText("Actualizar Ruta");
        jButtonActualizarRuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActualizarRutaActionPerformed(evt);
            }
        });

        jTextFieldBuscarProducto.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jTextFieldBuscarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBuscarProductoActionPerformed(evt);
            }
        });

        jButtonAsignarPedido.setBackground(new java.awt.Color(238, 0, 0));
        jButtonAsignarPedido.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jButtonAsignarPedido.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAsignarPedido.setText("Asignar");
        jButtonAsignarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAsignarPedidoActionPerformed(evt);
            }
        });

        jTablePedidosDeRuta.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jTablePedidosDeRuta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID_Pedido", "Cliente", "Direccion", "Fecha_Pedido"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Object.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTablePedidosDeRuta);

        jLabelNomRuta.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabelNomRuta.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelNomRuta.setText("Ruta n000");

        jButtonQuitarPedido.setBackground(new java.awt.Color(238, 0, 0));
        jButtonQuitarPedido.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jButtonQuitarPedido.setForeground(new java.awt.Color(255, 255, 255));
        jButtonQuitarPedido.setText("Quitar pedido a la ruta");
        jButtonQuitarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonQuitarPedidoActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel6.setText("Buscar Pedido");

        jTextFieldBuscarPPedido.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jTextFieldBuscarPPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBuscarPPedidoActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel7.setText("Pedido");

        jTablePedidos.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jTablePedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID_Pedido", "Direccion", "Cliente", "Fecha_Pedido"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane5.setViewportView(jTablePedidos);

        jComboColumnasProductos.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jComboColumnasProductos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID", "Direccion", "Cliente", "Fecha" }));

        jComboColumnasPedidos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID", "Nombre", "Cantidad", "P.Unitario", "Importe" }));

        Cabecera.setBackground(new java.awt.Color(174, 0, 0));
        Cabecera.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("MODIFICAR RUTA");
        Cabecera.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelNomRuta))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldBuscarProducto)
                        .addGap(18, 18, 18)
                        .addComponent(jComboColumnasProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonAsignarPedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonActualizarRuta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jButtonQuitarPedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldBuscarPPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jComboColumnasPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(Cabecera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Cabecera, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldBuscarProducto)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                                .addComponent(jLabelNomRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jComboColumnasProductos)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonAsignarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(jLabel6))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextFieldBuscarPPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jComboColumnasPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonQuitarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonActualizarRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 482, Short.MAX_VALUE))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonActualizarRutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActualizarRutaActionPerformed
    DefaultTableModel modeloRuta = (DefaultTableModel) jTablePedidosDeRuta.getModel();
    
    
    
    int idruta = RutasTabla.id_ruta;
    String nombreRuta = RutasTabla.nomruta;         


JOptionPane.showMessageDialog(this,
    "Ruta actualizada exitosamente.\n\n" +
    "ID Ruta: " + idruta + "\n" +
    "Nombre: " + nombreRuta,
    "Éxito", JOptionPane.INFORMATION_MESSAGE);


        if (modeloRuta.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this,
                "No hay pedidos asignados en la ruta. Agregue al menos uno.",
                "Pedido vacío", JOptionPane.WARNING_MESSAGE);
            return;
        }

        
        //obtenemos los id de los pedidos asignados en la ruta y los guardamos en la DB en su fila respectiva del pedido
        for (int i = 0; i < modeloRuta.getRowCount(); i++) {
            int idpedido = Integer.parseInt(modeloRuta.getValueAt(i, 0).toString());

            
            //asignamos los pedidos a la ruta en la BD
            ruta.AsignarPedidosARutas(idpedido,idruta);
        }
        

        JOptionPane.showMessageDialog(this,
            "Ruta actualizada exitosamente.",
            "Éxito", JOptionPane.INFORMATION_MESSAGE);

        // (Opcional) Limpieza de tabla después del registro
        modeloRuta.setRowCount(0);
        // Cerrar solo esta ventana
        dispose();
          
    }//GEN-LAST:event_jButtonActualizarRutaActionPerformed

    private void jTextFieldBuscarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBuscarProductoActionPerformed
        // TODO add your handling code here:
        
        jTablePedidos = new JTable(modelo);
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(modelo);
        jTablePedidos.setRowSorter(sorter);
        // Campo de búsqueda

        jTextFieldBuscarProducto.getDocument().addDocumentListener(new DocumentListener() {
            public void insertUpdate(DocumentEvent e) { filtrar(sorter); }
            public void removeUpdate(DocumentEvent e) { filtrar(sorter); }
            public void changedUpdate(DocumentEvent e) { filtrar(sorter); }
        });
    }//GEN-LAST:event_jTextFieldBuscarProductoActionPerformed

    private void jButtonQuitarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonQuitarPedidoActionPerformed
        // TODO add your handling code here:
            int fila = jTablePedidosDeRuta.getSelectedRow();
            int idpedido = Integer.parseInt(jTablePedidosDeRuta.getValueAt(fila, 0).toString());
            
        if (fila >= 0) {
            int confirmacion = JOptionPane.showConfirmDialog(this,
                "¿Está seguro que desea eliminar este pedido de la ruta?\nEsta acción no se puede deshacer.",
                "Confirmar eliminación",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE);

            if (confirmacion == JOptionPane.YES_OPTION) {
                DefaultTableModel modeloPedido = (DefaultTableModel) jTablePedidosDeRuta.getModel();
                int filaReal = jTablePedidosDeRuta.convertRowIndexToModel(fila);
                modeloPedido.removeRow(filaReal);

                JOptionPane.showMessageDialog(this,
                    "Pedido eliminado correctamente.",
                    "Éxito", JOptionPane.INFORMATION_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this,
                "Debe seleccionar un pedido de la ruta para eliminar.",
                "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        pedidos.QuitarPedidoRuta(idpedido);
        pedidos.obtenerTablaPedidosParaRuta(jTablePedidos,"IS NULL");
    }//GEN-LAST:event_jButtonQuitarPedidoActionPerformed

    private void jTextFieldBuscarPPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBuscarPPedidoActionPerformed
        // TODO add your handling code here:
        jTablePedidosDeRuta = new JTable(modelo2);
        TableRowSorter<DefaultTableModel> sorter2 = new TableRowSorter<>(modelo2);
        jTablePedidosDeRuta.setRowSorter(sorter2);
        // Campo de búsqueda

        jTextFieldBuscarPPedido.getDocument().addDocumentListener(new DocumentListener() {
            public void insertUpdate(DocumentEvent e) { filtrar2(sorter2); }
            public void removeUpdate(DocumentEvent e) { filtrar2(sorter2); }
            public void changedUpdate(DocumentEvent e) { filtrar2(sorter2); }
        });

    }//GEN-LAST:event_jTextFieldBuscarPPedidoActionPerformed

    private void jButtonAsignarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAsignarPedidoActionPerformed
        // TODO add your handling code here:
        int fila = jTablePedidos.getSelectedRow();
        if (fila >= 0) {
            int filaReal = jTablePedidos.convertRowIndexToModel(fila);
            String id = modelo.getValueAt(filaReal, 0).toString();
            String nombre = modelo.getValueAt(filaReal, 2).toString();
            String direccion = modelo.getValueAt(filaReal, 1).toString();
            String fecha =modelo.getValueAt(filaReal, 3).toString();

            
            JOptionPane.showMessageDialog(this,
            "Pedido agregado exitosamente:\n" +
            "Cliente:\n" + nombre +
            "Direccion:\n" + direccion +
            "ID Pedido: " + id,
            "Éxito", JOptionPane.INFORMATION_MESSAGE);
        
        DefaultTableModel modeloRuta = (DefaultTableModel) jTablePedidosDeRuta.getModel();
        modeloRuta.addRow(new Object[]{id, nombre, direccion, fecha});       
        }
    }//GEN-LAST:event_jButtonAsignarPedidoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RutasMOD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RutasMOD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RutasMOD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RutasMOD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PedidoMOD().setVisible(true);
            }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PedidoMOD().setVisible(true);
            }
        });*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Cabecera;
    private javax.swing.JButton jButtonActualizarRuta;
    private javax.swing.JButton jButtonAsignarPedido;
    private javax.swing.JButton jButtonQuitarPedido;
    private javax.swing.JComboBox<String> jComboColumnasPedidos;
    private javax.swing.JComboBox<String> jComboColumnasProductos;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelNomRuta;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTablePedidos;
    private javax.swing.JTable jTablePedidosDeRuta;
    private javax.swing.JTextField jTextFieldBuscarPPedido;
    private javax.swing.JTextField jTextFieldBuscarProducto;
    // End of variables declaration//GEN-END:variables
}
