/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyfinalbd2;

import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import javax.swing.table.TableRowSorter;
import proyfinalbd2.RutasCREAR;
import static proyfinalbd2.RutasCREAR.rFecha;
import proyfinalbd2.conexion.detalle_pedido;
import proyfinalbd2.conexion.pedidos;
import proyfinalbd2.conexion.ruta;

/**
 *
 * @author ASUS
 */
public class RutasAGREGAR extends javax.swing.JFrame {
    private DefaultTableModel modelo;
    private DefaultTableModel modelo2;
    private double total;
    public JTable tablaRutas;
    TableRowSorter<DefaultTableModel> sorter;
    TableRowSorter<DefaultTableModel> sorter2;
    
    

    private void filtrar(TableRowSorter<DefaultTableModel> sorter) {
        String texto = jTextFieldBuscarProducto.getText();
        
        int columna = jComboColumnasPedidosAgregar.getSelectedIndex();
        
        if (texto.trim().length() == 0) {
            sorter.setRowFilter(null);
        } else {
            sorter.setRowFilter(RowFilter.regexFilter("(?i)" + texto, columna));
        }
        
        
        
    }
    private void filtrar2(TableRowSorter<DefaultTableModel> sorter2) {
        String texto = jTextFieldBuscarPPedido.getText();
        int columna = jComboColumnasPedidosAgregados.getSelectedIndex();
        
        if (texto.trim().length() == 0) {
            sorter2.setRowFilter(null);
        } else {
            sorter2.setRowFilter(RowFilter.regexFilter("(?i)" + texto, columna));
        }
    }
    
   

    /**
     * Creates new form PedidoEscogerCliente
     */
    public RutasAGREGAR(JTable tablaRutas) {
        initComponents();
        pedidos.obtenerTablaPedidosParaRuta(jTablePedidos,"IS NULL");
        this.tablaRutas=tablaRutas;
        setLocationRelativeTo(null);
        setDefaultCloseOperation(RutasTabla.DISPOSE_ON_CLOSE);
        

        
        
        jLabelNomRuta.setText(ruta.obtenerUltimoIdRutaRegistrado() + " - " + RutasCREAR.nombre);
        
        modelo = (DefaultTableModel) jTablePedidos.getModel(); // Asignas el modelo
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(modelo);
        jTablePedidos.setRowSorter(sorter); // Conectas el sorter a la tabla
            
        modelo2 = (DefaultTableModel) jTableRuta.getModel(); // Asignas el modelo
        TableRowSorter<DefaultTableModel> sorter2 = new TableRowSorter<>(modelo2);
        jTableRuta.setRowSorter(sorter2); // Conectas el sorter a la tabla

    // Vinculas el filtro con el JTextField
    jTextFieldBuscarProducto.getDocument().addDocumentListener(new DocumentListener() {
        public void insertUpdate(DocumentEvent e) { filtrar(sorter); }
        public void changedUpdate(DocumentEvent e) { filtrar(sorter); }
        public void removeUpdate(DocumentEvent e) { filtrar(sorter); }
    });
       // Vinculas el filtro con el JTextField
    jTextFieldBuscarPPedido.getDocument().addDocumentListener(new DocumentListener() {
        public void insertUpdate(DocumentEvent e) { filtrar2(sorter2); }
        public void changedUpdate(DocumentEvent e) { filtrar2(sorter2); }
        public void removeUpdate(DocumentEvent e) { filtrar2(sorter2); }
    });
    
    

    }
    /**
     * Creates new form DatosCliente
     */


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jButtonRegistrarRuta = new javax.swing.JButton();
        jTextFieldBuscarProducto = new javax.swing.JTextField();
        jButtonAsignarPedido = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableRuta = new javax.swing.JTable();
        jLabelNomRuta = new javax.swing.JLabel();
        jButtonQuitarPedido = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldBuscarPPedido = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTablePedidos = new javax.swing.JTable();
        jComboColumnasPedidosAgregar = new javax.swing.JComboBox<>();
        jComboColumnasPedidosAgregados = new javax.swing.JComboBox<>();
        Cabecera = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(1000, 625));

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel2.setText("Ruta:");

        jButtonRegistrarRuta.setBackground(new java.awt.Color(238, 0, 0));
        jButtonRegistrarRuta.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jButtonRegistrarRuta.setForeground(new java.awt.Color(255, 255, 255));
        jButtonRegistrarRuta.setText("Registrar Ruta");
        jButtonRegistrarRuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarRutaActionPerformed(evt);
            }
        });

        jTextFieldBuscarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBuscarProductoActionPerformed(evt);
            }
        });

        jButtonAsignarPedido.setBackground(new java.awt.Color(238, 0, 0));
        jButtonAsignarPedido.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jButtonAsignarPedido.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAsignarPedido.setText("Asignar Pedido");
        jButtonAsignarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAsignarPedidoActionPerformed(evt);
            }
        });

        jTableRuta.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jTableRuta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID-Pedido", "Cliente", "Direccion", "Fecha_Pedido"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableRuta);

        jLabelNomRuta.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabelNomRuta.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelNomRuta.setText("Nueva Ruta n000");

        jButtonQuitarPedido.setBackground(new java.awt.Color(238, 0, 0));
        jButtonQuitarPedido.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jButtonQuitarPedido.setForeground(new java.awt.Color(255, 255, 255));
        jButtonQuitarPedido.setText("Quitar Pedido a la Ruta");
        jButtonQuitarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonQuitarPedidoActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel6.setText("Buscar Pedido");

        jTextFieldBuscarPPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBuscarPPedidoActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel7.setText("Pedido");

        jTablePedidos.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jTablePedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID_Pedido", "Direccion", "Cliente", "Fecha_Pedido"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane5.setViewportView(jTablePedidos);

        jComboColumnasPedidosAgregar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID", "Direccion", "Cliente", "Fecha" }));

        jComboColumnasPedidosAgregados.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID", "Cliente", "Direccion", "Fecha" }));

        Cabecera.setBackground(new java.awt.Color(174, 0, 0));
        Cabecera.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("NUEVA RUTA");
        Cabecera.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelNomRuta))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldBuscarProducto)
                        .addGap(18, 18, 18)
                        .addComponent(jComboColumnasPedidosAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 432, Short.MAX_VALUE)
                    .addComponent(jButtonAsignarPedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldBuscarPPedido)
                        .addGap(18, 18, 18)
                        .addComponent(jComboColumnasPedidosAgregados, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonRegistrarRuta, javax.swing.GroupLayout.DEFAULT_SIZE, 432, Short.MAX_VALUE)
                    .addComponent(jButtonQuitarPedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(38, 38, 38))
            .addComponent(Cabecera, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Cabecera, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelNomRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboColumnasPedidosAgregar)
                        .addComponent(jTextFieldBuscarProducto)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonAsignarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboColumnasPedidosAgregados, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextFieldBuscarPPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonQuitarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                        .addComponent(jButtonRegistrarRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRegistrarRutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarRutaActionPerformed
    DefaultTableModel modeloRuta = (DefaultTableModel) jTableRuta.getModel();
    
    long fecha = rFecha.getTime();
    java.sql.Date fecha_sql = new java.sql.Date(fecha);
    
    
    int idruta = ruta.obtenerUltimoIdRutaRegistrado();
    String nombreRuta = RutasCREAR.nombre;
    java.sql.Date fechaRuta = fecha_sql;          


JOptionPane.showMessageDialog(this,
    "Ruta creada exitosamente.\n\n" +
    "ID Ruta: " + idruta + "\n" +
    "Nombre: " + nombreRuta + "\n" +
    "Fecha de la Ruta: " + fechaRuta,
    "Éxito", JOptionPane.INFORMATION_MESSAGE);


        if (modeloRuta.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this,
                "No hay pedidos asignados en la ruta. Agregue al menos uno.",
                "Pedido vacío", JOptionPane.WARNING_MESSAGE);
            return;
        }

        
        //obtenemos los id de los pedidos asignados en la ruta y los guardamos en la DB en su fila respectiva del pedido
        for (int i = 0; i < modeloRuta.getRowCount(); i++) {
            int idpedido = Integer.parseInt(modeloRuta.getValueAt(i, 0).toString());

            
            //asignamos los pedidos a la ruta en la BD
            ruta.AsignarPedidosARutas(idpedido,idruta);
        }
        

        JOptionPane.showMessageDialog(this,
            "Ruta registrado exitosamente.",
            "Éxito", JOptionPane.INFORMATION_MESSAGE);

        // (Opcional) Limpieza de tabla después del registro
        ruta.mostrarRutasEnTabla(tablaRutas);
        modeloRuta.setRowCount(0);
        // Cerrar solo esta ventana
        dispose();

        
    }//GEN-LAST:event_jButtonRegistrarRutaActionPerformed

    private void jTextFieldBuscarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBuscarProductoActionPerformed
        // TODO add your handling code here:
        
        jTableRuta= new JTable(modelo2);
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(modelo2);
        jTableRuta.setRowSorter(sorter);
        // Campo de búsqueda

        jTextFieldBuscarPPedido.getDocument().addDocumentListener(new DocumentListener() {
            public void insertUpdate(DocumentEvent e) { filtrar(sorter); }
            public void removeUpdate(DocumentEvent e) { filtrar(sorter); }
            public void changedUpdate(DocumentEvent e) { filtrar(sorter); }
        });
    }//GEN-LAST:event_jTextFieldBuscarProductoActionPerformed

    private void jButtonQuitarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonQuitarPedidoActionPerformed
        // TODO add your handling code here:
            int fila = jTableRuta.getSelectedRow();

        if (fila >= 0) {
            int confirmacion = JOptionPane.showConfirmDialog(this,
                "¿Está seguro que desea eliminar este pedido de la ruta?\nEsta acción no se puede deshacer.",
                "Confirmar eliminación",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE);

            if (confirmacion == JOptionPane.YES_OPTION) {
                DefaultTableModel modeloPedido = (DefaultTableModel) jTableRuta.getModel();
                int filaReal = jTableRuta.convertRowIndexToModel(fila);
                modeloPedido.removeRow(filaReal);

                JOptionPane.showMessageDialog(this,
                    "Pedido eliminado correctamente.",
                    "Éxito", JOptionPane.INFORMATION_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this,
                "Debe seleccionar un pedido del pedido para eliminar.",
                "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonQuitarPedidoActionPerformed

    private void jTextFieldBuscarPPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBuscarPPedidoActionPerformed
        // TODO add your handling code here:
        jTableRuta = new JTable(modelo2);
        TableRowSorter<DefaultTableModel> sorter2 = new TableRowSorter<>(modelo2);
        jTableRuta.setRowSorter(sorter2);
        // Campo de búsqueda

        jTextFieldBuscarPPedido.getDocument().addDocumentListener(new DocumentListener() {
            public void insertUpdate(DocumentEvent e) { filtrar2(sorter2); }
            public void removeUpdate(DocumentEvent e) { filtrar2(sorter2); }
            public void changedUpdate(DocumentEvent e) { filtrar2(sorter2); }
        });

    }//GEN-LAST:event_jTextFieldBuscarPPedidoActionPerformed

    private void jButtonAsignarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAsignarPedidoActionPerformed
        // TODO add your handling code here:
        int fila = jTablePedidos.getSelectedRow();
        if (fila >= 0) {
            int filaReal = jTablePedidos.convertRowIndexToModel(fila);
            String id = modelo.getValueAt(filaReal, 0).toString();
            String direccion = modelo.getValueAt(filaReal, 2).toString();
            String cliente = modelo.getValueAt(filaReal, 1).toString();
            String fecha = modelo.getValueAt(filaReal, 3).toString();
            
            JOptionPane.showMessageDialog(this,
            "Pedido agregado exitosamente a la ruta:\n" +
            "ID Pedido: " + id + " - " + cliente,
            "Éxito", JOptionPane.INFORMATION_MESSAGE);
        
        DefaultTableModel modeloRuta = (DefaultTableModel) jTableRuta.getModel();
        modeloRuta.addRow(new Object[]{id, direccion, cliente, fecha});
        }     

    }//GEN-LAST:event_jButtonAsignarPedidoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RutasAGREGAR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RutasAGREGAR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RutasAGREGAR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RutasAGREGAR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PedidoAGREGAR().setVisible(true);
            }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PedidoAGREGAR().setVisible(true);
            }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PedidoAGREGAR().setVisible(true);
            }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PedidoAGREGAR().setVisible(true);
            }
        });*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Cabecera;
    private javax.swing.JButton jButtonAsignarPedido;
    private javax.swing.JButton jButtonQuitarPedido;
    private javax.swing.JButton jButtonRegistrarRuta;
    private javax.swing.JComboBox<String> jComboColumnasPedidosAgregados;
    private javax.swing.JComboBox<String> jComboColumnasPedidosAgregar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelNomRuta;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTablePedidos;
    private javax.swing.JTable jTableRuta;
    private javax.swing.JTextField jTextFieldBuscarPPedido;
    private javax.swing.JTextField jTextFieldBuscarProducto;
    // End of variables declaration//GEN-END:variables
}
